### ISSUE TITLE
Bug: Added word dublicate 

### ISSUE THREAD

**Issue by Dentrax** [metinUr/word-reminder#1]
This error occurs if there is a space at the beginning or in the middle or end of the word I added. 

Example: 
-The word I want to add: "Test ok"
-I can add these words: " Test ok", "Test ok ", "Test  ok", "Test   ok", "Test...ok"

**Comment by Mr-1311** [comment]
Well I think I forgot to check the spaces front, end and multiple spaces between words.
I checked and update project, thank you for contribute. :)
